/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import tottus.Empleados;

/**
 *
 * @author Mendoza
 */
public class AñadirEmp extends javax.swing.JFrame {

    /**
     * Creates new form AñadirEmp
     */
    public AñadirEmp() {
        initComponents();
        Empleados.InicioListaEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoVerdeOC = new javax.swing.JPanel();
        TITULO = new javax.swing.JLabel();
        TITULO1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        TITULO8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCódigo = new javax.swing.JTextField();
        TITULO9 = new javax.swing.JLabel();
        TITULO10 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        TITULO11 = new javax.swing.JLabel();
        TITULO12 = new javax.swing.JLabel();
        txtConfirmarContraseña = new javax.swing.JTextField();
        TITULO13 = new javax.swing.JLabel();
        CBPuesto = new javax.swing.JComboBox<>();
        BTNSalir = new javax.swing.JButton();
        BTNAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoVerdeOC.setBackground(new java.awt.Color(100, 176, 48));
        FondoVerdeOC.setPreferredSize(new java.awt.Dimension(600, 450));

        TITULO.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 255, 255));
        TITULO.setText("Añadir Empleado");

        TITULO1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TITULO1.setForeground(new java.awt.Color(255, 255, 255));
        TITULO1.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        TITULO8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TITULO8.setForeground(new java.awt.Color(255, 255, 255));
        TITULO8.setText("Apellido:");

        txtApellido.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        txtCódigo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        TITULO9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TITULO9.setForeground(new java.awt.Color(255, 255, 255));
        TITULO9.setText("Código:");

        TITULO10.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TITULO10.setForeground(new java.awt.Color(255, 255, 255));
        TITULO10.setText("Contraseña:");

        txtContraseña.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        TITULO11.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TITULO11.setForeground(new java.awt.Color(255, 255, 255));
        TITULO11.setText("Confirmar");

        TITULO12.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TITULO12.setForeground(new java.awt.Color(255, 255, 255));
        TITULO12.setText("Contraseña:");

        txtConfirmarContraseña.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        TITULO13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TITULO13.setForeground(new java.awt.Color(255, 255, 255));
        TITULO13.setText("Puesto:");

        CBPuesto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        CBPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Cajero", "Jefe" }));
        CBPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPuestoActionPerformed(evt);
            }
        });

        BTNSalir.setBackground(new java.awt.Color(255, 0, 0));
        BTNSalir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNSalir.setText("Salir");
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });

        BTNAñadir.setBackground(new java.awt.Color(68, 132, 0));
        BTNAñadir.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        BTNAñadir.setForeground(new java.awt.Color(255, 255, 255));
        BTNAñadir.setText("Añadir");
        BTNAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoVerdeOCLayout = new javax.swing.GroupLayout(FondoVerdeOC);
        FondoVerdeOC.setLayout(FondoVerdeOCLayout);
        FondoVerdeOCLayout.setHorizontalGroup(
            FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeOCLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TITULO1)
                            .addComponent(TITULO8)
                            .addComponent(TITULO9)
                            .addComponent(TITULO10)
                            .addComponent(TITULO11)
                            .addComponent(TITULO12)
                            .addComponent(TITULO13))
                        .addGap(52, 52, 52)
                        .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txtCódigo, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(txtConfirmarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(CBPuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeOCLayout.createSequentialGroup()
                        .addGap(0, 167, Short.MAX_VALUE)
                        .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeOCLayout.createSequentialGroup()
                                .addComponent(TITULO)
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeOCLayout.createSequentialGroup()
                                .addComponent(BTNSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(BTNAñadir)
                                .addGap(187, 187, 187))))))
        );
        FondoVerdeOCLayout.setVerticalGroup(
            FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(TITULO)
                .addGap(18, 18, 18)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITULO1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITULO8)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITULO9)
                    .addComponent(txtCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITULO13)
                    .addComponent(CBPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TITULO10)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                        .addComponent(TITULO11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TITULO12))
                    .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNAñadir))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FondoVerdeOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FondoVerdeOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        OpcionesJefe OJ = new OpcionesJefe();
        OJ.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BTNSalirActionPerformed

    private void BTNAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAñadirActionPerformed
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String código = txtCódigo.getText();
        String contraseña = txtContraseña.getText();
        String confirmar = txtConfirmarContraseña.getText();
        String puesto = "";
        int N = CBPuesto.getSelectedIndex();
        System.out.println(N);
        if (N == 1){
            puesto = "Cajero";
        }
        if (N == 2){
            puesto = "Jefe";
        }
        if(N!=0){
        if (contraseña.equals(confirmar)){
        if(contraseña == "" || confirmar == ""){
            BTNAñadir.setForeground(new java.awt.Color(255, 0, 0));
        }else{
            
            Empleados.agregarNuevoEmpleado(nombre,apellido, código,contraseña,confirmar,puesto);
            txtNombre.setText("");
            txtApellido.setText("");
            txtCódigo.setText("");
            txtContraseña.setText("");
            txtConfirmarContraseña.setText("");
            CBPuesto.setSelectedIndex(0);

        }
        }}else{
            BTNAñadir.setForeground(new java.awt.Color(255, 0, 0));
        }
        
        
        
         
        
    }//GEN-LAST:event_BTNAñadirActionPerformed

    private void CBPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPuestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Empleados.InicioListaEmpleados();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAñadir;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JComboBox<String> CBPuesto;
    private javax.swing.JPanel FondoVerdeOC;
    private javax.swing.JLabel TITULO;
    private javax.swing.JLabel TITULO1;
    private javax.swing.JLabel TITULO10;
    private javax.swing.JLabel TITULO11;
    private javax.swing.JLabel TITULO12;
    private javax.swing.JLabel TITULO13;
    private javax.swing.JLabel TITULO8;
    private javax.swing.JLabel TITULO9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtConfirmarContraseña;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCódigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
