
package GUI;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tottus.Productos;
import javax.swing.table.DefaultTableModel;
import tottus.ListaCompras;
import tottus.Clientes;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;



public class GestiónCompra extends javax.swing.JFrame {
    DefaultTableModel dtmListaCompras = new DefaultTableModel();
    
    private String puesto;
    
    public GestiónCompra() {
        initComponents();
        Productos.InicioListaProductos();
        Clientes.InicioListaClientes();
       dtmListaCompras.addColumn("Código");
       dtmListaCompras.addColumn("Nombre");
       dtmListaCompras.addColumn("Cantidad");
       dtmListaCompras.addColumn("Precio");
       dtmListaCompras.addColumn("PrecioCMR");
       dtmListaCompras.addColumn("PuntosCMR");
       this.tblListaCompras.setModel(dtmListaCompras);
    }
    
    
    
    
    
    
    
    
    
    
    
    public void SetPuesto(String puesto){
        this.puesto = puesto;
        PUESTO.setText(puesto);
    }
    public String getPuesto(){
    return puesto;
    }
    private void calcularImportes() {
    double sumaImporteNrml = 0;
    double sumaImporteAfl = 0;
    double sumaImportePtsAfl = 0;

    DefaultTableModel dtm = (DefaultTableModel) tblListaCompras.getModel();

    for (int i = 0; i < dtm.getRowCount(); i++) {
        sumaImporteNrml += Double.parseDouble(dtm.getValueAt(i, 3).toString());
        sumaImporteAfl += Double.parseDouble(dtm.getValueAt(i, 4).toString());
        sumaImportePtsAfl += Integer.parseInt(dtm.getValueAt(i, 5).toString());
    }

    ImporteNrml.setText(String.valueOf(sumaImporteNrml));
    ImporteAfl.setText(String.valueOf(sumaImporteAfl));
    ImportePtsAfl.setText(String.valueOf(sumaImportePtsAfl));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGMétodoPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCódigo = new javax.swing.JTextField();
        BTNAñadir = new javax.swing.JButton();
        BTNEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BTNTarjeta = new javax.swing.JRadioButton();
        BTNEfectivo = new javax.swing.JRadioButton();
        txtTarjetaoEfectivo = new javax.swing.JTextField();
        BTNPagar = new javax.swing.JButton();
        BTNSalir = new javax.swing.JButton();
        PUESTO = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCompras = new javax.swing.JTable();
        ImportePtsAfl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ImporteNrml = new javax.swing.JLabel();
        ImporteAfl = new javax.swing.JLabel();
        txtVuelto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(100, 176, 48));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestión de Compras");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código de Producto:");

        txtCódigo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        BTNAñadir.setBackground(new java.awt.Color(68, 132, 0));
        BTNAñadir.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        BTNAñadir.setForeground(new java.awt.Color(255, 255, 255));
        BTNAñadir.setText("Añadir");
        BTNAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAñadirActionPerformed(evt);
            }
        });

        BTNEliminar.setBackground(new java.awt.Color(68, 132, 0));
        BTNEliminar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        BTNEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BTNEliminar.setText("Eliminar");
        BTNEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Método de Pago:");

        BTNTarjeta.setBackground(new java.awt.Color(100, 176, 48));
        BGMétodoPago.add(BTNTarjeta);
        BTNTarjeta.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        BTNTarjeta.setText("Tarjeta");
        BTNTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTarjetaActionPerformed(evt);
            }
        });

        BTNEfectivo.setBackground(new java.awt.Color(100, 176, 48));
        BGMétodoPago.add(BTNEfectivo);
        BTNEfectivo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        BTNEfectivo.setText("Efectivo");

        txtTarjetaoEfectivo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtTarjetaoEfectivo.setText("Ingresar Tarjeta o Efectivo");
        txtTarjetaoEfectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTarjetaoEfectivoMouseClicked(evt);
            }
        });

        BTNPagar.setBackground(new java.awt.Color(68, 132, 0));
        BTNPagar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        BTNPagar.setForeground(new java.awt.Color(255, 255, 255));
        BTNPagar.setText("Pagar");
        BTNPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPagarActionPerformed(evt);
            }
        });

        BTNSalir.setBackground(new java.awt.Color(255, 0, 0));
        BTNSalir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNSalir.setText("Salir");
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });

        PUESTO.setForeground(new java.awt.Color(100, 176, 48));

        tblListaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListaCompras);

        ImportePtsAfl.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        ImportePtsAfl.setForeground(new java.awt.Color(255, 255, 255));
        ImportePtsAfl.setText(".");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Importe:");

        ImporteNrml.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        ImporteNrml.setForeground(new java.awt.Color(255, 255, 255));
        ImporteNrml.setText(".");

        ImporteAfl.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        ImporteAfl.setForeground(new java.awt.Color(255, 255, 255));
        ImporteAfl.setText(".");

        txtVuelto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtVuelto.setForeground(new java.awt.Color(100, 176, 48));
        txtVuelto.setText("Método de Pago:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(PUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(290, 290, 290))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTNAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNEliminar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ImporteNrml, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ImporteAfl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ImportePtsAfl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNSalir)
                                .addGap(99, 99, 99))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(BTNPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(BTNTarjeta)
                                        .addGap(18, 18, 18)
                                        .addComponent(BTNEfectivo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVuelto)
                                            .addComponent(jLabel3))))
                                .addGap(0, 16, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTarjetaoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(PUESTO))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BTNAñadir)
                    .addComponent(BTNEliminar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(txtVuelto)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNTarjeta)
                            .addComponent(BTNEfectivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTarjetaoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(BTNSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(BTNPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ImportePtsAfl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImporteNrml, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ImporteAfl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        OpcionesJefe OJ = new OpcionesJefe();
        OpcionesCajero OC = new OpcionesCajero();
        String P = getPuesto();
        boolean elegir = false;
        if(P.equals("Cajero")){
            OC.setVisible(true);
            this.dispose();
        }
        if(P.equals("Jefe")){
            OJ.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_BTNSalirActionPerformed

    private void txtTarjetaoEfectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTarjetaoEfectivoMouseClicked
        txtTarjetaoEfectivo.setText("");
    }//GEN-LAST:event_txtTarjetaoEfectivoMouseClicked

    private void BTNAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAñadirActionPerformed
        String[] info = new String[6];
        String codigo = txtCódigo.getText();
        Productos productoEncontrado = Productos.buscarProductoPorCodigo(codigo);
        
        info[0]= codigo;
        info[1]= productoEncontrado.getNombre();
        info[2]= "1";
        info[3]= String.valueOf(productoEncontrado.getPrecio());
        info[4]=String.valueOf(productoEncontrado.getPrecioAfiliado());
        info[5]=String.valueOf(productoEncontrado.getPuntosAfiliados());
        dtmListaCompras.addRow(info);
        txtCódigo.setText("");
        calcularImportes();
        
    }//GEN-LAST:event_BTNAñadirActionPerformed

    private void BTNEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarActionPerformed
        int fila = tblListaCompras.getSelectedRow();
    
        if (fila != -1) {
            DefaultTableModel dtm = (DefaultTableModel) tblListaCompras.getModel();
            dtm.removeRow(fila);
        }
        calcularImportes();
        
    }//GEN-LAST:event_BTNEliminarActionPerformed

    private void BTNPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPagarActionPerformed
        GraciasPorSuCompra GPSC = new GraciasPorSuCompra();
        
        
        if(BTNTarjeta.isSelected()){
        String NT = txtTarjetaoEfectivo.getText();
        Clientes cliente = Clientes.buscarClientePorTarjeta(NT);
        boolean Afiliado = cliente.isAfiliado();
        
        double Cantidad =cliente.getSaldo();
            if(Afiliado){
                double precio = Double.parseDouble(ImporteAfl.getText());
                double puntos = Double.parseDouble(ImportePtsAfl.getText());
                    if(Cantidad>=precio){
                        GPSC.SetVuelto(0.0);
                        GPSC.setVisible(true);
                       this.dispose();
                    }else{
                    JOptionPane.showMessageDialog(this, "Cantidad insuficiente, dar otro medio de pago", "Error", JOptionPane.ERROR_MESSAGE);
                    }
            }else{
                double precio = Double.parseDouble(ImporteNrml.getText());
                
                if(Cantidad>=precio){
                        GPSC.SetVuelto(0.0);
                        GPSC.setVisible(true);
                        this.dispose();
                }else{
                  JOptionPane.showMessageDialog(this, "Cantidad insuficiente, dar otro medio de pago", "Error", JOptionPane.ERROR_MESSAGE);}
            }
        }
        if(BTNEfectivo.isSelected()){
        double Cantidad = Double.parseDouble(txtTarjetaoEfectivo.getText());
        double precio = Double.parseDouble(ImporteNrml.getText());
            if(Cantidad>=precio){
                
                double vuelto = Cantidad-precio;
                GPSC.SetVuelto(vuelto);
                GPSC.setVisible(true);
                this.dispose();
            }else{
            JOptionPane.showMessageDialog(this, "Cantidad insuficiente, dar otro medio de pago", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }if(BTNEfectivo.isSelected()== false && BTNTarjeta.isSelected()== false){
            JOptionPane.showMessageDialog(this, "Ingresar un medio de pago", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_BTNPagarActionPerformed

    private void BTNTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNTarjetaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Productos.InicioListaProductos();
        Clientes.InicioListaClientes();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestiónCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestiónCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestiónCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestiónCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestiónCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGMétodoPago;
    private javax.swing.JButton BTNAñadir;
    private javax.swing.JRadioButton BTNEfectivo;
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JButton BTNPagar;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JRadioButton BTNTarjeta;
    private javax.swing.JLabel ImporteAfl;
    private javax.swing.JLabel ImporteNrml;
    private javax.swing.JLabel ImportePtsAfl;
    private javax.swing.JLabel PUESTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaCompras;
    private javax.swing.JTextField txtCódigo;
    private javax.swing.JTextField txtTarjetaoEfectivo;
    private javax.swing.JLabel txtVuelto;
    // End of variables declaration//GEN-END:variables
}
