/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import tottus.Empleados;

/**
 *
 * @author Mendoza
 */
public class OpcionesJefe extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    private String nombre;
    public OpcionesJefe() {
        initComponents();
        
    }
    public void SetNombre(String nombre){
        this.nombre = nombre;
        NOMBRE.setText(nombre);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoVerdeOC = new javax.swing.JPanel();
        SALUDO = new javax.swing.JLabel();
        BTNAñadir = new javax.swing.JButton();
        BTNEliminar = new javax.swing.JButton();
        BTNLista = new javax.swing.JButton();
        BTNCobrar = new javax.swing.JButton();
        BTNLista1 = new javax.swing.JButton();
        BTNCobrar1 = new javax.swing.JButton();
        SALUDO1 = new javax.swing.JLabel();
        FondoBlancoOC = new javax.swing.JPanel();
        LogoOC = new javax.swing.JLabel();
        BTNSalir = new javax.swing.JButton();
        NOMBRE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));

        FondoVerdeOC.setBackground(new java.awt.Color(100, 176, 48));

        SALUDO.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        SALUDO.setForeground(new java.awt.Color(255, 255, 255));
        SALUDO.setText("Bienvenido:");

        BTNAñadir.setBackground(new java.awt.Color(68, 132, 0));
        BTNAñadir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNAñadir.setForeground(new java.awt.Color(255, 255, 255));
        BTNAñadir.setText("AÑADIR COMPRA");

        BTNEliminar.setBackground(new java.awt.Color(68, 132, 0));
        BTNEliminar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BTNEliminar.setText("ELIMINAR COMPRA");

        BTNLista.setBackground(new java.awt.Color(68, 132, 0));
        BTNLista.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNLista.setForeground(new java.awt.Color(255, 255, 255));
        BTNLista.setText("LISTA COMPRAS");

        BTNCobrar.setBackground(new java.awt.Color(68, 132, 0));
        BTNCobrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNCobrar.setForeground(new java.awt.Color(255, 255, 255));
        BTNCobrar.setText("COBRAR");
        BTNCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCobrarActionPerformed(evt);
            }
        });

        BTNLista1.setBackground(new java.awt.Color(68, 132, 0));
        BTNLista1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNLista1.setForeground(new java.awt.Color(255, 255, 255));
        BTNLista1.setText("AÑADIR EMPLEADO");

        BTNCobrar1.setBackground(new java.awt.Color(68, 132, 0));
        BTNCobrar1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNCobrar1.setForeground(new java.awt.Color(255, 255, 255));
        BTNCobrar1.setText("AÑADIR PRODUCTO");
        BTNCobrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCobrar1ActionPerformed(evt);
            }
        });

        SALUDO1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        SALUDO1.setForeground(new java.awt.Color(255, 255, 255));
        SALUDO1.setText("Puesto: Jefe");

        FondoBlancoOC.setBackground(new java.awt.Color(255, 255, 255));

        LogoOC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Tottus.png"))); // NOI18N

        BTNSalir.setBackground(new java.awt.Color(255, 0, 0));
        BTNSalir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNSalir.setText("SALIR");
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoBlancoOCLayout = new javax.swing.GroupLayout(FondoBlancoOC);
        FondoBlancoOC.setLayout(FondoBlancoOCLayout);
        FondoBlancoOCLayout.setHorizontalGroup(
            FondoBlancoOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoBlancoOCLayout.createSequentialGroup()
                .addGroup(FondoBlancoOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoBlancoOCLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LogoOC))
                    .addGroup(FondoBlancoOCLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BTNSalir)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        FondoBlancoOCLayout.setVerticalGroup(
            FondoBlancoOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoBlancoOCLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(LogoOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(BTNSalir)
                .addGap(61, 61, 61))
        );

        NOMBRE.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FondoVerdeOCLayout = new javax.swing.GroupLayout(FondoVerdeOC);
        FondoVerdeOC.setLayout(FondoVerdeOCLayout);
        FondoVerdeOCLayout.setHorizontalGroup(
            FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                .addComponent(FondoBlancoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BTNLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNAñadir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNLista1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNCobrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoVerdeOCLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                                .addComponent(SALUDO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SALUDO1)))
                        .addGap(21, 21, 21))))
        );
        FondoVerdeOCLayout.setVerticalGroup(
            FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlancoOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SALUDO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALUDO1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNEliminar)
                .addGap(18, 18, 18)
                .addComponent(BTNLista)
                .addGap(18, 18, 18)
                .addComponent(BTNCobrar)
                .addGap(18, 18, 18)
                .addComponent(BTNLista1)
                .addGap(18, 18, 18)
                .addComponent(BTNCobrar1)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoVerdeOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoVerdeOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCobrarActionPerformed

    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTNSalirActionPerformed

    private void BTNCobrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCobrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCobrar1ActionPerformed

    
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesJefe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAñadir;
    private javax.swing.JButton BTNCobrar;
    private javax.swing.JButton BTNCobrar1;
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JButton BTNLista;
    private javax.swing.JButton BTNLista1;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JPanel FondoBlancoOC;
    private javax.swing.JPanel FondoVerdeOC;
    private javax.swing.JLabel LogoOC;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel SALUDO;
    private javax.swing.JLabel SALUDO1;
    // End of variables declaration//GEN-END:variables
}
