/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import tottus.Empleados;

/**
 *
 * @author Mendoza
 */
public class OpcionesJefe extends javax.swing.JFrame {
    
    /**
     * Creates new form Prueba
     */
    private String nombre;
    public OpcionesJefe() {
        initComponents();
        
    }
    public void SetNombre(String nombre){
        this.nombre = nombre;
        NOMBRE.setText(nombre);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoVerdeOC = new javax.swing.JPanel();
        SALUDO = new javax.swing.JLabel();
        BTNAñadir = new javax.swing.JButton();
        BTNAñadirEmp = new javax.swing.JButton();
        BTNAñadirPro = new javax.swing.JButton();
        SALUDO1 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();
        FondoBlancoOC = new javax.swing.JPanel();
        LogoOC = new javax.swing.JLabel();
        BTNSalir = new javax.swing.JButton();
        SALUDO2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        FondoVerdeOC.setBackground(new java.awt.Color(100, 176, 48));

        SALUDO.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        SALUDO.setForeground(new java.awt.Color(255, 255, 255));
        SALUDO.setText("Bienvenido:");

        BTNAñadir.setBackground(new java.awt.Color(68, 132, 0));
        BTNAñadir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNAñadir.setForeground(new java.awt.Color(255, 255, 255));
        BTNAñadir.setText("GESTIONAR COMPRA");
        BTNAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAñadirActionPerformed(evt);
            }
        });

        BTNAñadirEmp.setBackground(new java.awt.Color(68, 132, 0));
        BTNAñadirEmp.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNAñadirEmp.setForeground(new java.awt.Color(255, 255, 255));
        BTNAñadirEmp.setText("AÑADIR EMPLEADO");
        BTNAñadirEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAñadirEmpActionPerformed(evt);
            }
        });

        BTNAñadirPro.setBackground(new java.awt.Color(68, 132, 0));
        BTNAñadirPro.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNAñadirPro.setForeground(new java.awt.Color(255, 255, 255));
        BTNAñadirPro.setText("AÑADIR PRODUCTO");
        BTNAñadirPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAñadirProActionPerformed(evt);
            }
        });

        SALUDO1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        SALUDO1.setForeground(new java.awt.Color(255, 255, 255));
        SALUDO1.setText("Puesto:");

        NOMBRE.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(255, 255, 255));

        FondoBlancoOC.setBackground(new java.awt.Color(255, 255, 255));

        LogoOC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo Tottus.png"))); // NOI18N

        BTNSalir.setBackground(new java.awt.Color(255, 0, 0));
        BTNSalir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BTNSalir.setText("SALIR");
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoBlancoOCLayout = new javax.swing.GroupLayout(FondoBlancoOC);
        FondoBlancoOC.setLayout(FondoBlancoOCLayout);
        FondoBlancoOCLayout.setHorizontalGroup(
            FondoBlancoOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoBlancoOCLayout.createSequentialGroup()
                .addGroup(FondoBlancoOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoBlancoOCLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LogoOC))
                    .addGroup(FondoBlancoOCLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BTNSalir)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        FondoBlancoOCLayout.setVerticalGroup(
            FondoBlancoOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoBlancoOCLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(LogoOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(BTNSalir)
                .addGap(61, 61, 61))
        );

        SALUDO2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        SALUDO2.setForeground(new java.awt.Color(255, 255, 255));
        SALUDO2.setText("Jefe");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bolsacompras.png"))); // NOI18N

        javax.swing.GroupLayout FondoVerdeOCLayout = new javax.swing.GroupLayout(FondoVerdeOC);
        FondoVerdeOC.setLayout(FondoVerdeOCLayout);
        FondoVerdeOCLayout.setHorizontalGroup(
            FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                .addComponent(FondoBlancoOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BTNAñadir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNAñadirEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNAñadirPro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                                .addComponent(SALUDO)
                                .addGap(30, 30, 30)
                                .addComponent(SALUDO1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SALUDO2))
                            .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        FondoVerdeOCLayout.setVerticalGroup(
            FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoBlancoOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FondoVerdeOCLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FondoVerdeOCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SALUDO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALUDO1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALUDO2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BTNAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNAñadirEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNAñadirPro)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoVerdeOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoVerdeOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        PantallaPrincipalLogin PPL = new PantallaPrincipalLogin();
        PPL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNSalirActionPerformed

    private void BTNAñadirProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAñadirProActionPerformed
        AñadirProducto AP = new AñadirProducto();
        AP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNAñadirProActionPerformed

    private void BTNAñadirEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAñadirEmpActionPerformed
        AñadirEmp AE = new AñadirEmp();
        AE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNAñadirEmpActionPerformed

    private void BTNAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAñadirActionPerformed
        GestiónCompra GC = new GestiónCompra();
        GC.SetPuesto(SALUDO2.getText());
        GC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNAñadirActionPerformed

    
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesJefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesJefe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAñadir;
    private javax.swing.JButton BTNAñadirEmp;
    private javax.swing.JButton BTNAñadirPro;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JPanel FondoBlancoOC;
    private javax.swing.JPanel FondoVerdeOC;
    private javax.swing.JLabel LogoOC;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel SALUDO;
    private javax.swing.JLabel SALUDO1;
    private javax.swing.JLabel SALUDO2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
